### logout
POST http://localhost:80/api/logout
Accept: application/json
Authorization: Bearer 1|OsdA992PWS17braxSCgFx9d7ue1BgsxKOnDE9wc6ced23775

### login
POST http://localhost:80/api/login
Accept: application/json
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

### Register
POST http://localhost:80/api/register
Accept: application/json
Content-Type: application/json

{
    "username": "testuser",
    "firstname": "John",
    "lastname": "Doe",
    "email": "testuser@example.com",
    "auth_type": "local",
    "password": "password123",
    "password_confirmation": "password123"
}
