### Create Workspace
POST /api/workspaces HTTP/1.1
Content-Type: application/json
Accept: application/json
Host: localhost
Authorization: Bearer {{ token1 }}

{
    "name": "string",
    "description": "string"
}

> {%
    client.global.set("join_code", response.body.workspace.join_code)
    client.global.set("owner_workspace_id", response.body.workspace.workspace_id)
%}

### Join Workspace
POST /api/workspaces/join HTTP/1.1
Content-Type: application/json
Accept: application/json
Host: localhost
Authorization: Bearer {{ token2 }}

{
    "join_code": "{{ join_code }}"
}

> {%
    client.global.set("join_workspace_id", response.body.workspace.workspace_id)
%}

### Get My Workspace
GET /api/workspaces/my HTTP/1.1
Accept: application/json
Host: localhost
Authorization: Bearer {{ token1 }}

### Get Joined Workspace
GET /api/workspaces/joined HTTP/1.1
Accept: application/json
Host: localhost
Authorization: Bearer {{ token2 }}

### Leave Workspace
DELETE /api/workspaces/{{ join_workspace_id }}/leave HTTP/1.1
Accept: application/json
Host: localhost
Authorization: Bearer {{ token2 }}


### Get WorkspaceByID
GET /api/workspaces/3 HTTP/1.1
Accept: application/json
Host: localhost
Authorization: Bearer {{ token2 }}












